#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_health_check:
  path: /api/v1/health-check
  controller: App\Controller\HealthCheckController
  methods: [GET]

# User routes
api_register_user:
  path: /api/v1/users/register
  controller: App\Controller\User\RegisterController
  methods: [POST]

api_get_user_by_id:
  path: /api/v1/users/user/{email}
  controller: App\Controller\User\GetByEmailController
  methods: [GET]
